nodes:
  # Indexer server nodes
  indexer:
    - name: node-1
      ip: 34.32.10.65

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:

  # Dashboard node
  dashboard:
