

---
- hosts: wazuh_agents
  become: yes  
  tasks:
    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Copy Fail2Ban configuration
      template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify:
        - restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted

